port=53
listen-address=10.7.24.103,127.0.0.1
bind-interfaces

domain-needed
bogus-priv

address=/app.team1.test/10.7.15.18
address=/api.team1.test/10.7.15.18
interface=en0

cache-size=100
log-queries
